modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

[[mods]]
modId="portalmod"
version="0.4"
displayName="PortalMod"
logoFile="pack.png"
authors="SerialSniper, PhantomEye, LarsMans"
description='''
Portal in Minecraft, reimagined.
'''